-- 1. Add role column to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';

-- 2. Update existing policies for rooms
DROP POLICY IF EXISTS "Authenticated users can delete rooms" ON public.rooms;
DROP POLICY IF EXISTS "Authenticated users can insert rooms" ON public.rooms;
DROP POLICY IF EXISTS "Authenticated users can update rooms" ON public.rooms;

CREATE POLICY "Only admins can insert rooms" ON public.rooms
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Only admins can update rooms" ON public.rooms
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Only admins can delete rooms" ON public.rooms
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Seed Admin Users
DO $$
DECLARE
  admin_emails text[] := ARRAY['willian.santos1990@gmail.com', 'gil.araujo@repress.com.br', 'douglas.manoel@repress.com.br'];
  curr_email text;
  new_user_id uuid;
BEGIN
  FOREACH curr_email IN ARRAY admin_emails
  LOOP
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = curr_email) THEN
      new_user_id := gen_random_uuid();
      
      INSERT INTO auth.users (
        id, instance_id, email, encrypted_password, email_confirmed_at,
        created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
        is_super_admin, role, aud,
        confirmation_token, recovery_token, email_change_token_new,
        email_change, email_change_token_current,
        phone, phone_change, phone_change_token, reauthentication_token
      ) VALUES (
        new_user_id,
        '00000000-0000-0000-0000-000000000000',
        curr_email,
        crypt('Skip@Pass123!', gen_salt('bf')),
        NOW(), NOW(), NOW(),
        '{"provider": "email", "providers": ["email"]}',
        '{"name": "Admin"}',
        false, 'authenticated', 'authenticated',
        '', '', '', '', '',
        NULL, '', '', ''
      );

      -- Update the profile that was auto-generated by the trigger
      UPDATE public.profiles SET role = 'admin' WHERE id = new_user_id;
    ELSE
      -- Update existing profile role to admin
      UPDATE public.profiles
      SET role = 'admin'
      WHERE id = (SELECT id FROM auth.users WHERE email = curr_email);
    END IF;
  END LOOP;
END $$;
